### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by mischnic** [mimecorg/launchui#1]
You might want to take a look at the CLI app https://github.com/mischnic/proton-packager.  I created it before proton-native support was integrated into electron-builder. Only macOS is supported but it's structure should make it easy to support multiple OSs.

**Comment by mimecorg** [comment]
Thanks a lot. I'm planning to create a similar launchui-packager utility and I have very little experience with OS X, so it will be very helpful.

**Comment by mimecorg** [comment]
Hopefully all Mac related problems are fixed now.
