### ISSUE TITLE
zip not found

### ISSUE THREAD

**Issue by wormen** [mimecorg/launchui#3]
Downloading launchui-v0.1.4-win32-ai32.zip
Error: GET https://github.com/mimecorg/launchui/releases/download/v0.1.4/launchui-v0.1.4-win32-ai32.zip returned 404

**Comment by mimecorg** [comment]
The architecture should be ia32, not ai32.

**Comment by wormen** [comment]
this is your code that generated this reference
when downloading the archive automatically

**Comment by mimecorg** [comment]
But you pass the architecture as an option to that code. Otherwise it defaults to `process.arch` which shouldn’t return ai32.
