### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by bil-ash** [mimecorg/launchui#7]
Could you please specify which version of node you are using for launchui on windows?If it is 8.x.y could you please upgrade to 10.x.y LTS.
Actually I am using webassembly in my app and I believe that there will be some difference in wasm execution between node 10.x and 8.x.

**Comment by mimecorg** [comment]
Currently it's 8.11.1. I'm planning to release a version using node 10.x soon. In the meantime you can use on of the releases from the https://github.com/develar/launchui fork.

**Comment by bil-ash** [comment]
Thanks for pointing out to develar's fork. That solved my problem.Thanks. Closing the issue.
